### ISSUE TITLE
有时候好像会自动暂停？

### ISSUE THREAD

**Issue by TwinkleStarDust** [4o4E/zjooc-script#1]
播着播着会自动暂停，进度还在，再次点击开始学习后正常

**Comment by 4o4E** [comment]
如果多次遇到这个问题，按下f12，在`console`上方的过滤中输入`[zjooc] >`，然后把日志`console`中显示的日志发出来

如图

![image](https://user-images.githubusercontent.com/58851040/206893412-3da279e0-e544-45ad-91da-710fc020ed84.png)

**Comment by TwinkleStarDust** [comment]
![QQ截图20221211163110](https://user-images.githubusercontent.com/108475509/206894120-606ee599-e6ae-4556-a545-eba7
![Screenshot 2022-12-11 161945](https://user-images.githubusercontent.com/108475509/206894122-d5af4bb7-ca0b-40d1-b7d9-d5bfa9b54c3a.png)
8a8a5455.png)

大概这样

**Comment by 4o4E** [comment]
> ![QQ截图20221211163110](https://user-images.githubusercontent.com/108475509/206894120-606ee599-e6ae-4556-a545-eba7 ![Screenshot 2022-12-11 161945](https://user-images.githubusercontent.com/108475509/206894122-d5af4bb7-ca0b-40d1-b7d9-d5bfa9b54c3a.png) 8a8a5455.png)
> 
> 大概这样

发送日志，否则我无法确定问题

**Comment by TwinkleStarDust** [comment]
![QQ截图20221211163110](https://user-images.githubusercontent.com/108475509/206894489-79e056d7-35c6-4b4d-8702-d9386dd6d963.png)
欸我上次传了这张图片来着好像被吞了，就这一页，我好像也没找到在哪里导出log文件Orz；

**Comment by 4o4E** [comment]
是视频放到一半卡住了，还是怎么？

我没有遇到过这样的问题

---

另外你有试过手动暂停再播放吗，点了之后会继续播放吗

**Comment by TwinkleStarDust** [comment]
也不一定是播到一半，有时候播几秒钟就会自动暂停，有时候五分钟左右，有时候十分钟左右Orz。。再点击播放会重新加载一下继续播放，很奇怪Orz

**Comment by 4o4E** [comment]
暂停的时候暂停按钮是不是会像没暂停一样

**Comment by 4o4E** [comment]
另外他停住的时候，视频进度条和时间条是否还在动

**Comment by TwinkleStarDust** [comment]
被暂停的时候进度条会归零（如第一次回复图片的左下角），但是时间进度（10：10/11：0）会保留到被暂停的那个时间，暂停继续播放按钮有时候会出现有时候不会

**Comment by 4o4E** [comment]
更新了，尝试用新脚本替换旧脚本

**Comment by TwinkleStarDust** [comment]
我似乎发现当离开网课标签页面一段时间后再回来有大概率会卡顿（切回桌面开其他软件或者切到其他网页），所以我用PowerToys的始终置顶把网课网页缩在左下角置顶挂课，到目前为止只自动暂停了一次（卡在一个视频播放完加载下一个视频的时候，播放按键会有一个彩色的圈那个界面），手动返回再点进来选择课程可以正常继续挂机播放，算是好了吧qwq

**Comment by 4o4E** [comment]
> 我似乎发现当离开网课标签页面一段时间后再回来有大概率会卡顿（切回桌面开其他软件或者切到其他网页），所以我用PowerToys的始终置顶把网课网页缩在左下角置顶挂课，到目前为止只自动暂停了一次（卡在一个视频播放完加载下一个视频的时候，播放按键会有一个彩色的圈那个界面），手动返回再点进来选择课程可以正常继续挂机播放，算是好了吧qwq

你有试过新的脚本吗？

**Comment by TwinkleStarDust** [comment]
阿巴阿巴，有，新脚本也有同样的情况，我不清楚是不是有什么插件冲突了，我尝试了没安装任何插件的Edge和有插件的Chorome都会出现这种情况，不过无所谓暂停了手动点击一下开始学习就刷新继续了，总之还是感谢你的脚本 :D

**Comment by 4o4E** [comment]
> 阿巴阿巴，有，新脚本也有同样的情况，我不清楚是不是有什么插件冲突了，我尝试了没安装任何插件的Edge和有插件的Chorome都会出现这种情况，不过无所谓暂停了手动点击一下开始学习就刷新继续了，总之还是感谢你的脚本 :D

 我没办法复现，我自己这儿都是正常的
